### ISSUE TITLE
Lexical selection: matching a rule that should not

### ISSUE THREAD

**Issue by hectoralos** [apertium/apertium-lex-tools#1]
Tinc dues regles per seleccionar la traducció de cat a fra dels det pl "un" / "unes": l'opció per defecte i l'opció quan el determinant està precedit per una preposició acabada en "de".

La qüestió és que la segona regla es dispara en casos en que no hauria de passar:

```
echo "es fan a unes zones properes" | apertium -d . cat-fra-lextor
1:SELECT:0.80000:a<pr>:à<pr>
1:SELECT:1.00000:un<det><ind><f><pl>:quelque<det><ind><mf><pl>
^es<prn><pro><ref><p3><mf><sp>/se<prn><pro><ref><p3><mf><sp>$ ^fer<vblex><pri><p3><pl>/faire<vblex><pri><p3><pl>$ ^a<pr>/à<pr>$ ^un<det><ind><f><pl>/quelque<det><ind><mf><pl>$ ^zona<n><f><pl>/zone<n><f><pl>$ ^proper<adj><f><pl>/prochain<adj><f><pl>$^.<sent>/.<sent>$
```

La selecció de "quelque" no hauria de fer-se. Sembla com si la selecció anterior l'afectés. Les regles en qüestió són:

```
  <!-- uns >> des, quelques -->
  <rule weight="0.8">
    <match lemma="un" tags="det.*"><select lemma="un"/></match>
  </rule>
  <rule weight="1.0">
    <or> 
      <seq n="pr_de"/>
    </or>
    <or> 
      <match lemma="un" tags="det.ind.m.pl"><select lemma="quelque"/></match>
      <match lemma="un" tags="det.ind.f.pl"><select lemma="quelque"/></match>
    </or>
  </rule>

```

**Comment by hectoralos** [comment]
This seems to be a similar case:

<rules>
  <rule weight="0.6">
    <match lemma="João" tags="np.*"><select lemma="João"/></match>
  </rule>
  <rule weight="9.0">
    <match lemma="são" tags="adj.*"><select lemma="sant"/></match>
    <match lemma="João" tags="np.*"><select lemma="Joan"/></match>
  </rule>

  <rule weight="0.6">
    <match lemma="são" tags="adj.*"><select lemma="sa"/></match>
  </rule>
  <rule weight="1.0">
    <match lemma="são" tags="adj.*"><select lemma="sant"/></match>
    <match tags="np.ant.*"/>
  </rule>
</rules>

echo "são João" | apertium -d . por-cat-lex
1:SELECT<3>:são<adj><m><sg>:<select>sa<ANY_TAG>
1:SELECT<2>:João<np><ant><m><sg>:<select>Joan<ANY_TAG>
^são<adj><m><sg>/sa<adj><m><sg>$ ^João<np><ant><m><sg>/Joan<np><ant><m><sg>$^.<sent>/.<sent>$

If I delete the last two rules:

<rules>
  <rule weight="0.6">
    <match lemma="João" tags="np.*"><select lemma="João"/></match>
  </rule>
  <rule weight="9.0">
    <match lemma="são" tags="adj.*"><select lemma="sant"/></match>
    <match lemma="João" tags="np.*"><select lemma="Joan"/></match>
  </rule>
</rules>

echo "são João" | apertium -d . por-cat-lex
1:SELECT<2>:são<adj><m><sg>:<select>sant<ANY_TAG>
1:SELECT<2>:João<np><ant><m><sg>:<select>Joan<ANY_TAG>
^são<adj><m><sg>/sant<adj><m><sg>$ ^João<np><ant><m><sg>/Joan<np><ant><m><sg>$^.<sent>/.<sent>$

**Comment by unhammer** [comment]
Can you give the output of biltrans (or whatever step is  right before lrx-proc) for the above examples?

**Comment by hectoralos** [comment]
I couldn't reproduce the problem in por-cat. But I've tried to create a "minimal" case with French. The rule set is:
`<rules>
  <rule weight="0.8">
    <match lemma="un" tags="det.*">
      <select lemma="un"/>
    </match>
  </rule>
  <rule weight="1.0">
    <or>
      <match lemma="a partir de" tags="pr"/>
      <match lemma="des de" tags="pr"/>
      <match lemma="després de" tags="pr"/>
    </or>
    <or>
      <match lemma="un" tags="det.ind.m.pl">
        <select lemma="quelque"/>
      </match>
      <match lemma="un" tags="det.ind.f.pl">
        <select lemma="quelque"/>
      </match>
    </or>
  </rule>

  <rule weight="0.8">
    <match lemma="principi" tags="n.*">
      <select lemma="principe"/>
    </match>
  </rule>
  <rule weight="1.0">
    <or>
      <match lemma="a" tags="pr"/>
      <match lemma="a partir de" tags="pr"/>
      <match lemma="després" tags="pr"/>
      <match lemma="des de" tags="pr"/>
    </or>
    <match tags="det.*"/>
    <match lemma="principi" tags="n.*">
      <select lemma="début"/>
    </match>
  </rule>
</rules>
`
`echo "es fan a unes zones properes" | apertium -d . cat-fra-biltrans
^es<prn><pro><ref><p3><mf><sp>/se<prn><pro><ref><p3><mf><sp>$ ^fer<vblex><pri><p3><pl>/faire<vblex><pri><p3><pl>/poser<vblex><pri><p3><pl>$ ^a<pr>/à<pr>/en<pr>/dans<pr>$ ^un<det><ind><f><pl>/un<det><ind><mf><pl>/quelque<det><ind><mf><pl>$ ^zona<n><f><pl>/zone<n><f><pl>$ ^proper<adj><f><pl>/prochain<adj><f><pl>$^.<sent>/.<sent>$
`
`echo "es fan a unes zones properes" | apertium -d . cat-fra-lextor
1:SELECT:1.00000:un<det><ind><f><pl>:quelque<det><ind><mf><pl>
^es<prn><pro><ref><p3><mf><sp>/se<prn><pro><ref><p3><mf><sp>$ ^fer<vblex><pri><p3><pl>/faire<vblex><pri><p3><pl>/poser<vblex><pri><p3><pl>$ ^a<pr>/à<pr>/en<pr>/dans<pr>$ ^un<det><ind><f><pl>/quelque<det><ind><mf><pl>$ ^zona<n><f><pl>/zone<n><f><pl>$ ^proper<adj><f><pl>/prochain<adj><f><pl>$^.<sent>/.<sent>$`

If, for instance, one deletes the line with "des de" in the second or the forth rules, then the first rule is correctly selected instead of the second.

**Comment by unhammer** [comment]
I get 

```
$ clipboard >/tmp/fra.lrx
$ lrx-comp /tmp/fra.lrx /tmp/fra.bin
$ echo '^es<prn><pro><ref><p3><mf><sp>/se<prn><pro><ref><p3><mf><sp>$ ^fer<vblex><pri><p3><pl>/faire<vblex><pri><p3><pl>/poser<vblex><pri><p3><pl>$ ^a<pr>/à<pr>/en<pr>/dans<pr>$ ^un<det><ind><f><pl>/un<det><ind><mf><pl>/quelque<det><ind><mf><pl>$ ^zona<n><f><pl>/zone<n><f><pl>$ ^proper<adj><f><pl>/prochain<adj><f><pl>$^.<sent>/.<sent>$' \
  | lrx-proc -m /tmp/fra.bin -t
1:SELECT:0.80000:un<det><ind><f><pl>:un<det><ind><mf><pl>
^es<prn><pro><ref><p3><mf><sp>/se<prn><pro><ref><p3><mf><sp>$ ^fer<vblex><pri><p3><pl>/faire<vblex><pri><p3><pl>/poser<vblex><pri><p3><pl>$ ^a<pr>/à<pr>/en<pr>/dans<pr>$ ^un<det><ind><f><pl>/un<det><ind><mf><pl>$ ^zona<n><f><pl>/zone<n><f><pl>$ ^proper<adj><f><pl>/prochain<adj><f><pl>$^.<sent>/.<sent>$ 
```

Could you try upgrading apertium-lex-tools (`sudo apt update && sudo apt dist-upgrade` if you're using the Ubuntu/Debian nightlies) and try again?

**Comment by hectoralos** [comment]
I have upgraded apertium-lex-tools (it was not updated), and I did exactly as you:
```
$ lrx-comp /tmp/fra.lrx /tmp/fra.bin
4: 129@139
$ echo '^es<prn><pro><ref><p3><mf><sp>/se<prn><pro><ref><p3><mf><sp>$ ^fer<vblex><pri><p3><pl>/faire<vblex><pri><p3><pl>/poser<vblex><pri><p3><pl>$ ^a<pr>/à<pr>/en<pr>/dans<pr>$ ^un<det><ind><f><pl>/un<det><ind><mf><pl>/quelque<det><ind><mf><pl>$ ^zona<n><f><pl>/zone<n><f><pl>$ ^proper<adj><f><pl>/prochain<adj><f><pl>$^.<sent>/.<sent>$'   | lrx-proc -m /tmp/fra.bin -t
1:SELECT:1.00000:un<det><ind><f><pl>:quelque<det><ind><mf><pl>
^es<prn><pro><ref><p3><mf><sp>/se<prn><pro><ref><p3><mf><sp>$ ^fer<vblex><pri><p3><pl>/faire<vblex><pri><p3><pl>/poser<vblex><pri><p3><pl>$ ^a<pr>/à<pr>/en<pr>/dans<pr>$ ^un<det><ind><f><pl>/quelque<det><ind><mf><pl>$ ^zona<n><f><pl>/zone<n><f><pl>$ ^proper<adj><f><pl>/prochain<adj><f><pl>$^.<sent>/.<sent>$
```

**Comment by unhammer** [comment]
How is it with the newest nightly? ( apertium-lex-tools_0.2.1+g448~2a77a50b-2~xenial1_amd64 )

**Comment by hectoralos** [comment]
Unfortunately, I can't see any difference:
```
$ apt-show-versions -p apertium-lex-tools
apertium-lex-tools:amd64/xenial 0.2.1-1~xenial1 upgradeable to 0.2.1+g448~2a77a50b-2~xenial1
apertium-lex-tools:i386 not installed
$ lrx-comp test.un_quelque.lrx /tmp/fra.bin
4: 129@139
$ echo '^es<prn><pro><ref><p3><mf><sp>/se<prn><pro><ref><p3><mf><sp>$ ^fer<vblex><pri><p3><pl>/faire<vblex><pri><p3><pl>/poser<vblex><pri><p3><pl>$ ^a<pr>/à<pr>/en<pr>/dans<pr>$ ^un<det><ind><f><pl>/un<det><ind><mf><pl>/quelque<det><ind><mf><pl>$ ^zona<n><f><pl>/zone<n><f><pl>$ ^proper<adj><f><pl>/prochain<adj><f><pl>$^.<sent>/.<sent>$'   | lrx-proc -m /tmp/fra.bin -t
1:SELECT:1.00000:un<det><ind><f><pl>:quelque<det><ind><mf><pl>
^es<prn><pro><ref><p3><mf><sp>/se<prn><pro><ref><p3><mf><sp>$ ^fer<vblex><pri><p3><pl>/faire<vblex><pri><p3><pl>/poser<vblex><pri><p3><pl>$ ^a<pr>/à<pr>/en<pr>/dans<pr>$ ^un<det><ind><f><pl>/quelque<det><ind><mf><pl>$ ^zona<n><f><pl>/zone<n><f><pl>$ ^proper<adj><f><pl>/prochain<adj><f><pl>$^.<sent>/.<sent>$
```

**Comment by hectoralos** [comment]
Worked using:
`sudo apt -y dist-upgrade`
