### ISSUE TITLE
reproducible builds: lrx-comp binaries have nondeterministic contents

### ISSUE THREAD

**Issue by unhammer** [apertium/apertium-lex-tools#10]
See 
https://tests.reproducible-builds.org/debian/issues/unstable/nondeterminism_in_apertium_lrx_bin_files_generated_by_lrx_comp_issue.html

> The lrx-comp utility from apertium-lex-tools generates bin files withnondetermistic contents.

**Comment by mr-martian** [comment]
Most of what `lrx-comp` writes is with `alphabet.write()` and `transducer.write()`. Could the issue be writing the rule weights directly as ints an floats?

https://github.com/apertium/apertium-lex-tools/blob/12357e0df6f15912034b08a0bf72cd3d436a43c0/src/lrx_compiler.cc#L990-L1003

**Comment by TinoDidriksen** [comment]
Yup, that can absolutely cause it. That struct is 16 bytes on x86: int 4, padding 4, double 8. The padding bytes are never zeroed. Dumping a struct to disk as-is is not portable code. Fixing this will require a binary format bump, but luckily we have the functionality for that now.
