### ISSUE TITLE
lexical selection rules don't seem to be longest-match

### ISSUE THREAD

**Issue by jonorthwash** [apertium/apertium-lex-tools#13]
Issue as [originally reported on sourceforge](https://sourceforge.net/p/apertium/tickets/119/):

> Between a context-free and context-sensitive rule that select different readings, which one applies seems to be random. In fact, currently I can only get the context-free one to apply—it seems to be overriding the context-sensitive one even when the latter should match.
> 
> However, I believe the most specific rules should match first, and then the context-free ones should match only if no more specific rules match.

The work-around offered there was to use weights.  To which I responded:

> Yes, I'm aware that that's currently the best way to get around this issue, but I'm not yet convinced that it's not an issue...

Is this in fact not an issue, then?

**Comment by unhammer** [comment]
I'm fairly sure they're not intended to be longest match, though @ftyers would know better. I just put higher weights on longer patterns.

**Comment by ftyers** [comment]
The `-m` option picks the best combination according to matches and weights. Without this it does an "optimal coverage" algorithm. I recommend using the `-m` option as the other one may be buggy.

**Comment by unhammer** [comment]
Should we close this as notabug? Or do you have situations where weighting doesn't fix things / is cumbersome?

**Comment by ftyers** [comment]
I'm going to close this, reopen if there is a case where weighting won't do the same thing.

**Comment by jonorthwash** [comment]
Do I understand correctly that both using `-m` _and_ adding weights are required?  Or do I pick up undertones of the latter not always being needed, based on 
> "optimal coverage" algorithm

?
