### ISSUE TITLE
lrx-proc is slow

### ISSUE THREAD

**Issue by unhammer** [apertium/apertium-lex-tools#19]
With just a few hundred rules, lrx-proc easily becomes the slowest part of the pipeline; in nno-nob it is 4x slower than the cg (thousands of rules). Since lt-proc is so much faster, and in principle should work quite similarly, it seems like it should be possible to speed up lrx-proc. 

It got 5x slower as of https://github.com/apertium/apertium-lex-tools/pull/18 but that did also solve an important bug.

poormansprofiler.org says we spend a lot of time copying states(?):
```
      4 std::vector<std::pair<int,,State::copy(State,State::State(State,__gnu_cxx::new_allocator<State>::construct<State,,std::allocator_traits<std::allocator<State>,std::vector<State,,LRXProcessor::processME,main
      4 _int_malloc,__GI___libc_malloc,operator,State::copy(State,State::State(State,__gnu_cxx::new_allocator<State>::construct<State,,std::allocator_traits<std::allocator<State>,std::vector<State,,LRXProcessor::processME,main
      3 State::apply(int,,State::step(int,,LRXProcessor::processME,main
      3 <main_arena>),_int_malloc,__GI___libc_malloc,operator,std::vector<State::TNodeState,,State::copy(State,State::State(State,LRXProcessor::processME,main
      2 std::vector<State::TNodeState,,State::copy(State,State::State(State,__gnu_cxx::new_allocator<State>::construct<State,,std::allocator_traits<std::allocator<State>,std::vector<State,,LRXProcessor::processME,main
      2 State::copy(State,State::State(State,__gnu_cxx::new_allocator<State>::construct<State,,std::allocator_traits<std::allocator<State>,std::vector<State,,LRXProcessor::processME,main
      2 malloc_consolidate,_int_malloc,__GI___libc_malloc,operator,std::vector<State::TNodeState,,State::copy(State,State::State(State,LRXProcessor::processME,main
      2 <main_arena>,,__GI___libc_malloc,operator,std::vector<State::TNodeState,,State::copy(State,State::State(State,LRXProcessor::processME,main
      2 _int_malloc,__GI___libc_malloc,operator,std::vector<std::pair<int,,State::copy(State,State::State(State,LRXProcessor::processME,main
      2 _int_free,State::apply(int,,State::step(int,,LRXProcessor::processME,main
```
I guess this output would be more useful with shorter functions, but it seems we're spending a lot of our time in the loop at line 1089: https://github.com/apertium/apertium-lex-tools/blob/master/lrx_processor.cc#L1087 which copies a State and pushes (another copy?) onto new_states.

**Comment by unhammer** [comment]
@TinoDidriksen do you see anything obvious?

**Comment by TinoDidriksen** [comment]
I  see a lot of copying that could probably all be eliminated.

**Comment by unhammer** [comment]
Well, I see one weird thing: new_states keeps adding an initial State for every character it sees in input, so a long word will have a very long list of new_states that all contain the exact same string (each State also contains the whole sequence of input that lead to it)

**Comment by unhammer** [comment]
I'm currently testing if simply removing `alive_states.push_back(*initial_state);` on line 1120 will fix things – so far it at least seems to remove the bug where a rule looking for lemma "den" would match input lemma "en" :-)

**Comment by mr-martian** [comment]
It might also help to minimize the transducer in lrx-comp. Since the rules are completely separate paths that shouldn't reintroduce #12 and it would bring the number of states back down somewhat. (so in the example in #12 the paths for A would overlap again, but not the ones for the latter parts of the rules)

**Comment by unhammer** [comment]
So 
https://github.com/apertium/apertium-lex-tools/commit/5d06817543882cdbf17fbbf16d7c99ae3ebd29ce helps quite a bit, and seems to have no regressions (just progressions). Unless you were relying on `lemma` being a suffix match :-S

Does anyone use `lrx-proc` without `-m`? In that case, the fix should probably go to[ line 752 (`process`)](https://github.com/apertium/apertium-lex-tools/blob/5d06817543882cdbf17fbbf16d7c99ae3ebd29ce/lrx_processor.cc#L752) too.

**Comment by unhammer** [comment]
@mr-martian yeah I saw there were no hits for `minimize` in `lrx_compiler`. OTOH, rules are fairly short (and non-overlapping –  minimization makes the most sense when you can overlap), so I do wonder how much you'd gain. Try it and see?

**Comment by mr-martian** [comment]
Text: http://www.gutenberg.org/ebooks/470 (67714 words)
Pair: eng->spa

| State | Size | Time (real, avg of 3 runs) |
| --- | --- | --- |
| Prior to 5d06817 | 127808 | 38.6s ± 1s |
| With 5d06817 | 141353 | 6.34s ± 0.01s |
| With minimization | 138466 | 0.66 ± 0.03s |

Output of all 3 versions is identical.

**Comment by unhammer** [comment]
Mind running that again with newest master @mr-martian ?

**Comment by mr-martian** [comment]
No difference in output.

Minimization run is currently at 1.99s with this change averaging 1.204s ± 0.004s.

**Comment by unhammer** [comment]
That's interesting

* original 7eb4467 **4m14s**
* with 5d06817 **1m8s**
* with 5d06817 and 01f9b46 **13s**
* with 5d06817 and 01f9b46 and 4165215 **10s**
* with 5d06817 and 4165215 **36s**

So it seems both no-copying and minimising help, but together their effects cancel out a bit. Presumably less states to copy when minimised?

In any case, I think this can be closed now, at least for `lrx-proc -m`. 

Does anyone actually use lrx-proc without the -m? @ftyers should that be deprecated, or is it worth applying the changes there too?

**Comment by jonorthwash** [comment]
`apertium-init` I believe defaults to creating pairs without `-m`.  So there are probably a bunch of pairs out there without it.

**Comment by mr-martian** [comment]
@jonorthwash apertium-init uses -m as of 22 days ago.

**Comment by unhammer** [comment]
Should those pairs be changed to using `-m`? (Because I think there was some bug in the non-m-code and @ftyers  suggested just using `-m` everywhere.)

**Comment by mr-martian** [comment]
Or make both with and without ```-m``` do the same thing?

**Comment by ftyers** [comment]
@unhammer without the `-m` should be deprecated.

**Comment by jonorthwash** [comment]
Yes, the pairs should probably be changed.

But note that three semesters worth of me teaching Computational Linguistics has resulted in a couple dozen translation pairs without `-m` that are not publicly accessible for the most part.  And when they are publicly accessible, they aren't always easily findable.  E.g., https://github.com/daniellerossetti/Kaingang-Portuguese-Translator.

So yes, deprecation sounds right, with a warning of some sort.  Either at run time or generation of modes files?  The idea would be that if someone is using a pair without `-m` they should get enough info to know that they should add `-m` if they expect things to keep working right.

**Comment by unhammer** [comment]
`lrx-proc` could print something (once) to stderr when run without `-m`? 

> Or make both with and without -m do the same thing?

↑ any reason not to do this? If it's deprecated anyway, people shouldn't be depending on the feature.

**Comment by jonorthwash** [comment]
>>Or make both with and without -m do the same thing?
>
>↑ any reason not to do this? If it's deprecated anyway, people shouldn't be depending on the feature.

It's a little unintuitive to essentially require that users use the switch every time.  Switches should be optional and add something.  Otherwise its use is just vestigial.

**Comment by unhammer** [comment]
Just two minutes ago I managed to forget the switch myself and got confused as to why the weights were wrong :-)

**Comment by unhammer** [comment]
Moving the discussion about -m to #24, lrx-proc is no longer slow so I'll close this :)
