### ISSUE TITLE
Python co-opted install step

### ISSUE THREAD

**Issue by TinoDidriksen** [apertium/apertium-lex-tools#23]
@Vaydheesh (CC: @unhammer), when running `make install` only the Python parts are installed. Somehow, the added Python code prevents the usual install of `lrx-comp`, `lrx-proc`, `multitrans`.

(@Vaydheesh has been invited to the repo.)

**Comment by unhammer** [comment]
Strange, I get them installed, but maybe that's a fluke. It differs from libdivvun in not having any subdirs from before (libdivvun sets `SUBDIRS = src …` and then `SUBDIRS += python`), does it help to do `SUBDIRS = . python`  (with `.`)?

**Comment by Vaydheesh** [comment]
I am unable to reproduce the bug. Here are the steps that I have followed
- fresh clone of `apertium-lex-tools`
- `./autogen.sh --enable-python-bindings && make -j 4 && make install DESTDIR=/tmp/foo`
- `tree /tmp/foo`

```
/tmp/foo
└── usr
    └── local
        ├── bin
        │   ├── lrx-comp
        │   ├── lrx-proc
        │   └── multitrans
        └── lib
            └── python3.7
                └── site-packages
                    ├── apertium_lex_tools-0.2.1-py3.7.egg-info
                    ├── _lextools.cpython-37m-x86_64-linux-gnu.so
                    ├── lextools.py
                    └── __pycache__
                        └── lextools.cpython-37.pyc
```
- 

> `SUBDIRS = . python` (with `.`

This doesn't have any affect on the output, maybe this can fix the issue.

**Comment by TinoDidriksen** [comment]
That was indeed bogus. I had forgotten to add an install file for apertium-lex-tools itself. I've rolled back the commit to this repo.
