### ISSUE TITLE
Make -m default, deprecate non-m

### ISSUE THREAD

**Issue by unhammer** [apertium/apertium-lex-tools#24]
Cf. comments from https://github.com/apertium/apertium-lex-tools/issues/19#issuecomment-498336677 and down

>  without the -m should be deprecated.

I think the best would be to make `lrx-proc` do what `lrx-proc -m` does now (still accepting the `-m` switch). 

If the non-m behaviour is buggy, it's probably just as well if there's no way to turn it on from the cli.

**Comment by xavivars** [comment]
Should we go ahead on this?

**Comment by TinoDidriksen** [comment]
Does any pair currently use it without `-m`?

**Comment by unhammer** [comment]
I think some do by mistake (due to apertium-init) 

Den Søn 14 jul 2019, klokka 09:47, skreiv Tino Didriksen:
