### ISSUE TITLE
Add Metalrx Features

### ISSUE THREAD

**Issue by mr-martian** [apertium/apertium-lex-tools#33]
`lrx-comp` should deal with metalrx features directly:

- [x] `<repeat>` - see #32 
- [x] `<def-seq>` and `<seq>` - see #34 
- [ ] `<def-macro>` and `<macro>`

One question I have, though, is how to structure the file:

```xml
<lrx>
  <def-macros>
    <def-macro>
  </def-macros>
  <def-seqs>
    <def-seq>
  </def-seqs>
  <rules>
    <rule>
  </rules>
</lrx>
```
The obvious way, but would require updating every pair that uses lex-tools even if they don't use metalrx.

```xml
<rules>
  <rule>
  <def-seq>
  <def-macro>
  <rule>
  <def-seq>
  <rule>
</rules>
```
Less structured, but also less updating.

The third option is to allow either `<lrx>` or `<rules>` to be the root element, though this is probably the messiest solution of all.

**Comment by unhammer** [comment]
I'd prefer solution 1 – apertium is still centralised enough that we could automatically fix all the lrx files with a little simple scripting

**Comment by ftyers** [comment]
Are these really `def-seq` ? Aren't they more like sets? (While we're changing the format)

**Comment by xavivars** [comment]
I think you're right, in most cases, as the "pseud-seq" is inside an OR, it becomes a set

**Comment by ftyers** [comment]
I think of `seq` as short for `sequence` which is more like `a b c` instead of `a | b | c`

**Comment by xavivars** [comment]
Yes, definitely, but even in regexp (as in LRX), you can convert a "sequence" (`abc`), into a set, by wrapping it into something else (`[abc]`, or `<or>`).

But I agree, the `seq` functionality needed from metalrx is actually a "set" functionality

**Comment by unhammer** [comment]
I've been using them like

```
      <def-seq n="søkkbart">
        <or>
          <match lemma="tråler"/>
          <match lemma="båt"/>
          <match lemma="gummibåt"/>
          <match lemma="fartøy"/>
          <match lemma="skip"/>
        </or>
      </def-seq>
```

– aren't they inserted literally where you use a seq? They used to be :)

**Comment by ftyers** [comment]
Hmm, interesting. I don't know, but perhaps this could be clarified?

**Comment by unhammer** [comment]
https://github.com/apertium/apertium-lex-tools/blob/master/src/lrx_compiler.cc#L405-L459

**Comment by unhammer** [comment]
It definitely works that way too. Without the or, it's *not* a set, but a sequence.

**Comment by mr-martian** [comment]
I implemented them as sequence because most uses had `<def-seq><or> ... </or></def-seq>` and I imagined that actual sequences might be desirable at some point.

**Comment by unhammer** [comment]
That also makes it more general (like TEMPLATE in CG)
