### ISSUE TITLE
lrx-proc selects wrong word for lemma=""

### ISSUE THREAD

**Issue by unhammer** [apertium/apertium-lex-tools#36]
```
$ cat bug.lrx
<rules>
  <rule>
    <match lemma="foo" tags="adv">
      <select lemma="" tags="adv"/>
    </match>
  </rule>
</rules>

$ lrx-comp bug.lrx bug.autolex.bin
1: 11@10

$ echo '^foo<adv>/bar<adv>/<adv>$' | lrx-proc -t -m bug.autolex.bin
2:SELECT:1.00000:foo<adv>:bar<adv>
^foo<adv>/bar<adv>$
```

**Comment by mr-martian** [comment]
The current behavior has `lemma=""` completely equivalent to `lemma="*"`.

**Comment by unhammer** [comment]
https://github.com/apertium/apertium-lex-tools/blob/master/src/lrx_compiler.cc#L617-L620

**Comment by unhammer** [comment]
if(lemma == L"")
  {
    currentState = transducer.insertSingleTransduction(alphabet(0, alphabet(L"<ANY_CHAR>")), currentState);
    int localLast = localCurrentState;
    localCurrentState = recogniser.insertSingleTransduction(alphabet(alphabet(L"<ANY_CHAR>"),0), localCurrentState);
    recogniser.linkStates(localCurrentState, localLast, 0);
    key = key + L"<ANY_CHAR>";
  }

**Comment by unhammer** [comment]
@ftyers why is this?

**Comment by unhammer** [comment]
OK, I've checked the related issues: 
- https://github.com/apertium/apertium-lex-tools/pull/16
- https://github.com/apertium/apertium-lex-tools/issues/9
- https://github.com/apertium/apertium-lex-tools/pull/15
- https://github.com/apertium/apertium-lex-tools/issues/14

and although we do want `lemma="*"` to work as in transfer (match any lemma), the reason for making `lemma=""` equal to `lemma="*"` seems to be that lemma is *implicitly* set to the empty string if it's not specified at all in the XML, so users had to explicitly mention lemma even if they only cared about tags. But *there is a difference between specifying an empty lemma and not specifying a lemma*.

We want `lemma="*" tags="foo"` to be equal to `tags="foo"`, matching any lemma, but `lemma=""` should require that the lemma is the empty string.
