### ISSUE TITLE
Enhancement: matching depending on capitalization

### ISSUE THREAD

**Issue by hectoralos** [apertium/apertium-lex-tools#41]
It would be useful if we could select one lemma or another depending on whether the source lemma is capitalized or not.

**Comment by hectoralos** [comment]
I have understood how it can be done, but this feature seems to be undocumented. I'll write some words in the wiki.

**Comment by hectoralos** [comment]
Still, it seems there is no form to select a lemma depending on the capitalization if we cannot write down the actual lemma. For instance, I want to translate "William" to "William" as a rule, but to "Guillem" if it is followed by "the" + a capitalized noun or adjective (e.g. "William the Conqueror").

**Comment by unhammer** [comment]
Maybe regex support in lemmas would be a solution? That could be quite useful for other things too :)

**Comment by ftyers** [comment]
I don't like the idea of having a regex in the lemma, as in in the `lemma="[A-Z][a-z]+"`, but for example having something like
```
<rule weight="2.0">
<match lemma="William"><select lemma="Guillem"/></match>
<match tags="det.def.*"/>
<or>
  <match tags="n.*" case="Aa"/>
  <match tags="adj.*" case="Aa"/>
</or>
</rule>
```
Would be pretty ok and serve our needs.

**Comment by unhammer** [comment]
It would have to be a different attribute (`rlemma` or something) if it were regex, so we know how to interpret special characters. Regex could be handy for matching multiword verbs (`rlemma=".*#.*"`) or punctuation or heads of lexicalised compounds (`<def-seq n="woof"/><or><match lemma="hund"/><match lemma=".*hund" tags="n.*.cmp"/></</`).

But yeah, the case="…" looks nicer for this use-case; without a way to refer to predefined attributes you'd have to copy-paste your case-regex all over the place.

**Comment by xavivars** [comment]
Yesterday, @ftyers implemented a "suffix" that is essentially the same as `lemma=".*hund"`.

**Comment by ftyers** [comment]
@unhammer  I think from a design point of view having specialised attributes rather than using regex is the nicer way of doing this. Adjusting the compiler is not an awful lot of work (the suffix thing took about 10 minutes) and is a lot cleaner than allowing regular expressions. E.g. for the multiword verbs we could go with `contains="#"`. For punctuation I think it would be great to have some builtins, e.g. `<match punct/>` (although this would be easier if we had better unicode support.

**Comment by unhammer** [comment]
hehe ok I should've pulled before checking :)

**Comment by ftyers** [comment]
I've added both `contains` and `case` in 49b0d7f.
