### ISSUE TITLE
suffix of a lemma matches lemma when inside an <or> with a tag match

### ISSUE THREAD

**Issue by unhammer** [apertium/apertium-lex-tools#44]
https://github.com/apertium/apertium-lex-tools/compare/suffix-overmatch?expand=1 has the test case of a bug where the suffix of a lemma is matched (lrx-proc gives `wronglm`, should get `rightlm`).

 (In nno-nob, input lemma `som` matches a rule with `lemma="om"`) 

It seems the `<or><match tags="sent.clb"/>` is necessary (a workaround is splitting it into two rules).

**Comment by mr-martian** [comment]
![blah](https://user-images.githubusercontent.com/5350777/85077375-1e4d2280-b190-11ea-8934-3e1d323842b8.png)

Yep, the transducer is wrong.

I thought it might be something about `<or>` recording the start state wrong, but if I change the order I still get the same structure.

**Comment by mr-martian** [comment]
The transducer is being minimized wrong. I'll have a fix up shortly.

**Comment by xavivars** [comment]
Was this really a bug? Or an undocumented feature? There are rules that were relying on this behavior...

https://github.com/apertium/apertium-spa-cat/blob/master/apertium-spa-cat.spa-cat.metalrx#L8380

**Comment by ftyers** [comment]
That's definitely a bug, but to replicate the functionality as:
```
<match suffix="ismo" tags="n.*"/>
```
would work

**Comment by xavivars** [comment]
does this work? :O

**Comment by unhammer** [comment]
Definitely a bug. All the copy-pasting from making workarounds for it was making my spacebar overheat.

I don't see `suffix` in https://github.com/apertium/apertium-lex-tools/blob/suffix-overmatch/src/lrx_compiler.cc#L23-L47 . Another use-case for [regex](https://github.com/apertium/apertium-lex-tools/issues/41#issuecomment-647373269)? :)

**Comment by xavivars** [comment]
@unhammer : https://github.com/apertium/apertium-lex-tools/blob/master/src/lrx_compiler.cc#L36
