### ISSUE TITLE
Do something sensible about n vs. n.*

### ISSUE THREAD

**Issue by ftyers** [apertium/apertium-lex-tools#49]
So at the moment `n` is `<n>` and `n.*` is `<n>(<ANY_TAG>)+`, there is no way to refer to `<n>(<ANY_TAG>)*`, and that might be kind of useful, e.g. in languages where there is `<n>` and `<n><pl>`. 

It was done like this to reflect how transfer does pattern matching. 

I can think of a couple of options:
1. Make `n.*` be equivalent to `<n>(<ANY_TAG>)*` this would generally do the right thing because it would work for languages that do that and also for languages that have `<sg>/<pl>`, but it would make matching work less like transfer.
2. Make it possible to choose the behaviour of `.*` by using an attribute to the `<rules>`, something like `<rules glob="plus">` and `<rules glob="star">` where one of them could be default (probably `glob="plus"`). 

Any thoughts?

**Comment by unhammer** [comment]
I agree it makes more sense for the glob to be `(<ANY_TAG>)*`. But if it's changed, is there then any way to refer to `(<ANY_TAG>)+`? (Can we explicitly use `<ANY_TAG>` inside lrx rules? That would be great, then I could remove my `<def-seq n="ANY_TAG">`.)

… is there a safe way to convert transfer rules also to change the default there as well? If there is, one could potentially do a conversion of all t?x rule files. If you have an ANY_TAG symbol, I think you could safely do it by changing `cat-item tags="foo.*"` to `cat-item tags="foo.ANY_TAG.*"` etc.

**Comment by ftyers** [comment]
Perhaps we could do something like: 

* `n.?` = `<n>(<ANY_TAG>)?`
* `n.+` = `<n>(<ANY_TAG>)+`
* `n.*` = `<n>(<ANY_TAG>)*`

(I don't like the idea of using `<ANY_TAG>` directly in the rules, it's an implementation detail, not strictly part of the formalism.

**Comment by unhammer** [comment]
ANY_TAG would be useful for distinguishing knowns vs unknowns (without regex, we can't check for '*' in lemma), but perhaps that could also have some special attribute

**Comment by ftyers** [comment]
Unknowns should have a separate attribute, e.g. it could be something like 
```
<match case="Aa" unknown="true"/>
```

**Comment by jonorthwash** [comment]
> Perhaps we could do something like:
> 
>     * `n.?` = `<n>(<ANY_TAG>)?`
> 
>     * `n.+` = `<n>(<ANY_TAG>)+`
> 
>     * `n.*` = `<n>(<ANY_TAG>)*`
> 
> 
> (I don't like the idea of using `<ANY_TAG>` directly in the rules, it's an implementation detail, not strictly part of the formalism.

I would be very much in favour of this.  Especially if you could do things like `n.*.acc` or `n.?.?.acc`.

**Comment by mr-martian** [comment]
Unknowns could also be with `tags=""` (I think that might be how they are now).

**Comment by hectoralos** [comment]
I sometimes need to distinguish between adv and adv.itg, and between num, num.aa and num.nn. So, if any change is done, the possibility to clearly distinguish between one-tag word forms and two-tag word forms (or n-tag and n+1-tag word forms) should be preserved.
