### ISSUE TITLE
compiled format incompatability?

### ISSUE THREAD

**Issue by unhammer** [apertium/apertium-lex-tools#51]
`fromsource` is compiled from 52e6a2587645cae7a08d9b5735edcb565fad0f93 with lex-tools Version: 0.2.4+g483~47222e3c-1~eoan1

`monday` is from the .deb package Version: 1.3.0+g2547~52e6a258-1~sid1 
presumably compiled from 52e6a2587645cae7a08d9b5735edcb565fad0f93, but with lex-tools from Sunday.

The one from the deb doesn't select anything. The one compiled today does (when run using lex-tools 47222e3c)

[bins.zip](https://github.com/apertium/apertium-lex-tools/files/4821420/bins.zip)

```
$ echo '^myndighet<n><m><pl><def>/mynde<n><m><pl><def>/makt<n><f><pl><def>/fullmakt<n><f><pl><def>/autoritet<n><m><pl><def>/myndigheit<n><f><pl><def>/styresmakt<n><f><pl><def>$' | lrx-proc -t -m monday.nob-nno.autolex.bin 
^myndighet<n><m><pl><def>/mynde<n><m><pl><def>/makt<n><f><pl><def>/fullmakt<n><f><pl><def>/autoritet<n><m><pl><def>/myndigheit<n><f><pl><def>/styresmakt<n><f><pl><def>$

$ echo '^myndighet<n><m><pl><def>/mynde<n><m><pl><def>/makt<n><f><pl><def>/fullmakt<n><f><pl><def>/autoritet<n><m><pl><def>/myndigheit<n><f><pl><def>/styresmakt<n><f><pl><def>$' | lrx-proc -t -m fromsource.nob-nno.autolex.bin 
2:SELECT:1.00000:myndighet<n><m><pl><def>:6:styresmakt<n><f><pl><def>
^myndighet<n><m><pl><def>/styresmakt<n><f><pl><def>$
```

**Comment by TinoDidriksen** [comment]
Hexdump of the files differs from first bytes. https://github.com/apertium/apertium-lex-tools/commit/0f8eb652a62e8c43353ad94c45c0f57a54a01e6e does change the compiler by making a whole section of code not run when `lemma == L"*"`

**Comment by TinoDidriksen** [comment]
Need to add binary files to the test suite so that this cannot happen again. Maybe also add version info to the format, so that lex-tools can at least give an error message instead of misbehaving.

**Comment by TinoDidriksen** [comment]
All 180 nightly packages that use lex-tools were rebuilt, minus the few that [failed to build](https://apertium.projectjj.com/apt/logs/nightly/20200624-lex-tools.log). I have verified that the nob-nno testcase now outputs the correct result.

Also verified that the added binary tests actually work. Curiously, the new binaries work with the old code, but old binaries break with new code.

Deployed everything that built to beta.
