### ISSUE TITLE
Support Macros

### ISSUE THREAD

**Issue by mr-martian** [apertium/apertium-lex-tools#55]
This is the final component of #33 

### current status

As far as I can find, macros are currently used in
- fra-cat
- cat-ita
- cat-srd
- spa-cat
- oci-fra
- por-cat

Currently the syntax for defining these is
```xml
<def-macros>
  <def-macro name="noms_propis">
    <rule>
      <match lemma="{{p1}}" tags="np.*"><select lemma="{{p2}}"/></match>
      <!-- whatever else -->
    </rule>
    ...
  </def-macro>
</def-macros>
```
and the syntax for invoking them is
```xml
<macro name="noms_propis" p1="Carles" p2="Charles" />
```

Parameter numbers do not currently go higher than 4 and parameters are not used as anything other than entire lemmas.

The listed pairs each have 1-3 macros per rule file for a total of 21.

### implementation

In order to support this or something like it I think we either need some way of referring back to earlier locations in the xml or an intermediate representation of the rule structure.

I don't see any way of implementing the first option using `xmlreader.h`, so this would probably require switching the xml parser, which would entail changing most of the code in the compiler.

The second option, on the other hand, would probably result in duplicating quite a bit of the code in the compiler or else substantially rewriting it to also use the intermediate representation.

### design

Do we want to support macros exactly as-is?

Should macros specify number of parameters?

Should macro invocation be more like
```xml
<macro name="noms_propis">
  <param v="Carles"/>
  <param v="Charles"/>
</macro>
```
so it's more representable in a DTD (#11)?

Maybe we also want inside the macro to be more like
```xml
<match plemma="1"/>
```

**Comment by ftyers** [comment]
I don't like the `{{{1}}}` hack. It does not feel like a good XML data representation. I would do something like:

```
<def-macros>
  <def-macro name="noms_propis" npar="2">
    <rule>
      <match tags="np.*"><param pos="1" attr="lemma"/> <select><param pos="2" attr="lemma"/></select></match>
      <!-- whatever else -->
    </rule>
    ...
  </def-macro>
</def-macros>
```

```
<rule>
<call-macro name="noms_propis2">
  <with-param v="Carles"/>
  <with-param v="Charles"/>
</macro>
</rule>
```

Echos a bit the way transfer works, should be DTD/Schemable. And doesn't do text processing over XML.

**Comment by xavivars** [comment]
Actually this shouldn't be callés macros, but templates.

And `{{{1}}}` is not really a "hack", because the file with `{{{1}}}` is a templatized XML using a common templating format (mustache, twig, jinja, liquid,...). But I agree is not XML-like, so if this goes to lex-tools core, we should find a better representation.

**Comment by ftyers** [comment]
@xavivars sorry about the "hack" thing! I agree with you and @unhammer that these should be called `templates` and not `macros`. Let me update my proposal:
```
<templates>
  <template name="noms_propis" npar="2">
    <rule>
      <match tags="np.*"><param pos="1" attr="lemma"/> <select><param pos="2" attr="lemma"/></select></match>
      <!-- whatever else -->
    </rule>
    ...
  </template>
</templates>
```
Then something like:
```
<rule>
<use-template name="noms_propis2">
  <with-param v="Carles"/>
  <with-param v="Charles"/>
</use-template>
</rule>
```

**Comment by xavivars** [comment]
No offense taken! I don't consider "hack" being a negative word, I just wanted to mention that it was actually using the "de-facto standard" most of the templating languages use for replacement

https://mustache.github.io/mustache.5.html

**Comment by ftyers** [comment]
@hectoralos @jaumeortola do you both have any preferences?

**Comment by mr-martian** [comment]
It occurs to me that at least the proper noun examples could be handled by allowing `<select>` in `<def-seq>`.

```xml
<def-seq n="n_prop">
  <or>
    <match lemma="Carles" tags="np.*"><select lemma="Charles"/></match>
    <!-- etc. -->
  </or>
</def-seq>

<rule>
  <seq n="n_prop"/>
  <!-- whatever -->
</rule>
```

There are also macros that deal with verbs, I'd have to read them again to know what they're actually doing.

**Comment by hectoralos** [comment]
1. Actually, "macros" are at least used in another released pair: apertium-srd-ita. And I'm using them in my current GSoC pair apertium-fra-frp.

2. I really don't have any preferences about syntax, but I'd like to ask for:
* A very easy way to change from the current syntax to the new one.
* The possibility to use loops and sequences without the macros/templates. This would make them quite a lot more powerful and general.

(Off-topic: is it currently possible to have two or more loops in a single rule? This would make them more compact.)

**Comment by ftyers** [comment]
@hectoralos what do you mean by loops ?

**Comment by hectoralos** [comment]
@ftyers :

```
    <repeat from="0" upto="1">
      <match tags="adv"/>
    </repeat>
```

**Comment by ftyers** [comment]
I left these out of the original formalism because I was worried about the computational complexity, but if people have been using them without problems, then I would say we should instead do something like:
```xml
<optional>
   <any>
      <match tags="adv"/>
   </any>
</optional>
```
There is no real barrier to doing it, after all the matching portion is an FST.

**Comment by hectoralos** [comment]
Well, this is the same as an upto-1 loop, but I have to often use upto-2 for French adverbs (pas toujours, etc.). And I copied a very useful hack from Jaume for things like these:

```
  <rule weight="1.0">
    <or>
      <match lemma="achetar" tags="vblex.*"/>
      <match lemma="agetar" tags="vblex.*"/>
      <match lemma="dèjonar" tags="vblex.*"/>
      <match lemma="denar" tags="vblex.*"/>
      <match lemma="dinar" tags="vblex.*"/>
      <match lemma="sopar" tags="vblex.*"/>
      <match lemma="cenar" tags="vblex.*"/>
      <match lemma="marendar" tags="vblex.*"/>
      <match lemma="sèrvir" tags="vblex.*"/>
      <match lemma="balyér" tags="vblex.*"/>
      <match lemma="donar" tags="vblex.*"/>
      <match lemma="plat" tags="n.*"/>
      <match lemma="platèl" tags="n.*"/>
      <match lemma="platelâ" tags="n.*"/>
      <match lemma="fruit" tags="n.*"/>
    </or>
    <repeat from="0" upto="6">
      <match tags="*"/>
    </repeat>
    <or>
      <match lemma="cortelyâjo" tags="n.*"><select lemma="légume"/></match>
      <match lemma="jardenâjo" tags="n.*"><select lemma="légume"/></match>
    </or>
  </rule>
```

**Comment by ftyers** [comment]
Yep, this is scanning, which in principle could also be permitted. Have you found that it causes large memory usage or decrease in speed ?

**Comment by hectoralos** [comment]
No, I haven't noticed anything empirically, not I have done any measurements.

**Comment by mr-martian** [comment]
> (Off-topic: is it currently possible to have two or more loops in a single rule? This would make them more compact.)

Yes. The way I implemented them, rules can have arbitrarily many `<repeat>`s, and you can probably even nest them if you really want to.

**Comment by ftyers** [comment]
@hectoralos is the `[0...6]` a placeholder for `*` ? Would it be more useful to have a star operation? Or are there times where you would like to specify exactly 0-5 adverbs or something else?

**Comment by hectoralos** [comment]
Well, I try to contain a combinatorial explosion. If this is not a problem, the number is relatively conventional. In any case, it is hard to think that, say, more than one determinant will come together, or more than 2 or 3 adverbs, etc. Wouldn't help to be able to add an upper (and a lower) bound?

By the way, I should add that I have very few rules which match anything, so the number of words that trigger scanning is very little. It is very unlikely that they could take a big amount of resources. But potentially, this could happen, I imagine.

**Comment by xavivars** [comment]
@ftyers 

> I left these out of the original formalism because I was worried about the computational complexity, but if people have been using them without problems...

They are already natively supported 

https://github.com/apertium/apertium-lex-tools/pull/32/files

**Comment by ftyers** [comment]
@xavivars yeah, I saw, my point was that rather than just supporting a finite number and multiplying the states, we could just have a loopback that would consume as many as it finds.

**Comment by xavivars** [comment]
I'm not sure if that would be better....

**Comment by ftyers** [comment]
Well, I think that having finite numbers is a bit arbitrary (e.g. is it exactly 5 and not 6 ... or 3 that we need for a certain feature), and the fewer arbitrary things the better. I  think it would be better just to allow `<any>` and then if necessary we can "unroll" that to a finite number.

**Comment by xavivars** [comment]
Is definitely arbitrary, I agree. But it's usually based on analysis of texts (I guess as arbitrary as the scores that apertium-anaphora has).

But I'll leave it up to you ;)

**Comment by hectoralos** [comment]
> > (Off-topic: is it currently possible to have two or more loops in a single rule? This would make them more compact.)
> 
> Yes. The way I implemented them, rules can have arbitrarily many `<repeat>`s, and you can probably even nest them if you really want to.

@mr-martian, currently I imagine it is not yet released. I tried and got this error:

```
lrx-comp .deps/apertium-fra-frp.frp-fra.lrx frp-fra.autolex.bin
Error (322): Invalid node '<ERROR-multiple-repeats>'.
```

**Comment by mr-martian** [comment]
@hectoralos fra-frp is still using `metalrx-to-lrx.xslt` which errors on multiple `<repeats>`. Everything in the xslt is now supported, so in your makefile you can change
```
.deps/%.metalrx: %.metalrx .deps/.d
	apertium-metalrx $< $@

.deps/%.lrx: .deps/%.metalrx
	apertium-metalrx-to-lrx $< $@
```
to
```
.deps/%.lrx: %.metalrx .deps/.d
	apertium-metalrx $< $@
```
and it should all work

**Comment by hectoralos** [comment]
@mr-martian, it works. Thanks a lot!
