### ISSUE TITLE
LRX suffix attribute not working

### ISSUE THREAD

**Issue by jaumeortola** [apertium/apertium-lex-tools#56]
Translation spa>cat, sentence `Rayaba en la libreta`. 

Expected translation: `Ratllava en la llibreta`.

It should not match this rule [LRX rule ](https://github.com/apertium/apertium-spa-cat/blob/master/apertium-spa-cat.spa-cat.metalrx#L8435). But the rule matches and the translation is `Ranejava en la llibreta`.

**Comment by mr-martian** [comment]
There was a typo in the code that made `suffix=` have the expected behavior of `contains=` and vice-versa. See if 8f114b7 fixes the issue for you.

**Comment by jaumeortola** [comment]
Thank you. I am not compiling the source code, but @MarcRiera confirms that it works as expected.
