### ISSUE TITLE
Dependences and versions fail installing in Centos 7

### ISSUE THREAD

**Issue by renderpci** [apertium/apertium-lex-tools#63]
Hi

I try to install Apertium in CentOS 7 and it fail with the versions and dependences, mainly with apertium-lex-tools.

I try to install with yum from the _home_TinoDidriksen_night_ repository and _home_TinoDidriksen_release_, in both cases the apertium-lex-tools package send a error like:

`yum install apertium-spa`

> Error: Package: apertium-spa-1.2.1.g1558.f978d038-1.1.noarch (home_TinoDidriksen_nightly)
>           Need: apertium-lex-tools >= 0.2.7
>            Available: apertium-lex-tools-0.2.3.g464.34337c67-1.1.x86_64 (home_TinoDidriksen_nightly)

I try to install with the source code , I can install lttoolbox and Apertium but I can't compile and instal this git repository and I get a error

> lrx_compiler.cc: In member function ‘void LRXCompiler::write(FILE*)’:
> lrx_compiler.cc:1071:42: error: no matching function found for call to ‘weight::weight(<brace-enclosed initializer list>)’
>      weight record{it.first, "", it.second};
>                                           ^
> lrx_compiler.cc:1071:42: note: candidates are:
> In file included from lrx_compiler.cc:18:0:
> ./weight.h:25:8: nota: weight::weight()
>  struct weight {
>         ^
> ./weight.h:25:8: note: candidate expects 0 arguments, 3 were provided
> ./weight.h:25:8: note: constexpr weight::weight(const weight&)
> ./weight.h:25:8: note:  candidate expects 1 arguments, 3 were provided
> ./weight.h:25:8: note: constexpr weight::weight(weight&&)
> ./weight.h:25:8: note:  candidate expects 1 arguments, 3 were provided
> make[1]: *** [lrx_compiler.o] Error 1

The question is, how can install apertium-lex-tools?, all language pair need it, and or is too old (0.2.3 in the repository and 0.2.7 needed) or can't build.

Thanks in advance.

Alex

**Comment by TinoDidriksen** [comment]
EL7 fails to build: https://build.opensuse.org/package/show/home:TinoDidriksen:nightly/apertium-lex-tools

Looks like I need to add Devtoolset.

**Comment by TinoDidriksen** [comment]
Fixed in packaging. As for building from source, you need a newer compiler capable of C++14. The packages build with https://www.softwarecollections.org/en/scls/rhscl/devtoolset-7/ package `devtoolset-7-gcc-c++` but there are newer versions available.

**Comment by renderpci** [comment]
Thanks TinoDidriksen

Now  _apertium-lex-tools_ is working, but now the error come from other file: _apertium-separable_

yum install apertium-spa

> Error: Package: apertium-spa-1.2.1.g1558.f978d038-1.1.noarch (home_TinoDidriksen_nightly)
>            Need: apertium-separable >= 0.3.6
>            Available: apertium-separable-0.3.5.g247.69031478-3.8.x86_64 (home_TinoDidriksen_nightly)
>                apertium-separable = 0.3.5.g247.69031478-3.8

Can you fix it?

Thanks in advance.

Alex

**Comment by TinoDidriksen** [comment]
Fixed. apertium-separable 0.3.6 is now in the RPM builder.

**Comment by renderpci** [comment]
Hi!

Great, thanks.
