### ISSUE TITLE
scripts/Makefile should be generated by configure, not hardcode versions

### ISSUE THREAD

**Issue by vivekvardhanadepu** [apertium/apertium-lex-tools#67]
`g++ -Wall -Wextra -O3 -g process_tagger_output.cc -o process-tagger-output -I/usr/local/include/apertium-3.4 -I/usr/local/include/lttoolbox-3.3 -I/usr/include/apertium-3.4 -I/usr/include/lttoolbox-3.3 -I/usr/include/libxml2 -llttoolbox3 -lapertium3 -lxml2`
By default, it searches for apertium-3.4 and lttoolbox-3.3. Need to make it check for other supported versions automatically

**Comment by unhammer** [comment]
That's not a check though. `./configure` does the checking, and finds where lttoolbox/apertium are installed, and ends up creating the Makefile with those paths it found. The actual version constraints should be in `configure.ac`.

**Comment by vivekvardhanadepu** [comment]
oops:sweat_smile:. I didn't do `./configure` as it was not mentioned in https://wiki.apertium.org/wiki/Install_Apertium_core_by_compiling. So, should it be updated? :thinking:

**Comment by unhammer** [comment]
`./configure` is run by `./autogen.sh`

**Comment by vivekvardhanadepu** [comment]
`./autogen.sh` is not updating the scripts/Makefile. I have just run it

**Comment by vivekvardhanadepu** [comment]
But, as @unhammer mentioned shouldn't it run `./configure`?:thinking:. (running `./configure` separately updated the Makefile) or you mean it won't run `./configure`?

**Comment by unhammer** [comment]
Oh, I failed to notice you actually wrote `scripts/` in the title of the issue :) Yeah, that file should probably be renamed Makefile.am so configure can generate a Makefile

**Comment by vivekvardhanadepu** [comment]
@TinoDidriksen @unhammer Thanks!!
