### ISSUE TITLE
Lexical selection: Begin of sentence (or of text)

### ISSUE THREAD

**Issue by hectoralos** [apertium/apertium-lex-tools#88]
It would be interesting to have some way of being able to refer in the selection to the beginning of the text we are translating. For sentences that are not the first one, we have the full stop of the previous sentence to refer to the beginning of the sentence, but for the first sentence we don't have any reference. I am thinking on something like:

```
  <rule weight="1.0">
      <or>
        <match tags="[begin of sentence]"/>
        <match tags="sent"/>
      </or>
      <match lemma="aquí" tags="adv"><select lemma="voilà"/></match>
  </rule>
```

**Comment by hectoralos** [comment]
This kind of syntax would be fine for me.

**Comment by mr-martian** [comment]
similarly to https://github.com/apertium/apertium/issues/144#issuecomment-962510085, we could maybe also have an optional specification for an end-of-sentence delimiter and then `<begin/>` would be a general beginning-of-sentence token (which would simply not match if it appears anywhere other than the beginning of the rule).

**Comment by hectoralos** [comment]
Maybe. There may be problems also at the end of the text if a full stop or another punctuation mark is missing, although I don't remember I have experienced any (except in the tagger, but CG perfectly solves the issues there).

**Comment by rinkydevi** [comment]
hey @hectoralos  i would like to work on this issue, can u provide me info to proceed

**Comment by hectoralos** [comment]
@rinkydevi , I don't think I can. I'm a user that asks for an enhancement, not a programmer. I have no idea about the actual code in Apertium.
