### ISSUE TITLE
Possible issue when two "selects" within an "or"

### ISSUE THREAD

**Issue by hectoralos** [apertium/apertium-lex-tools#89]
There are quite a lot of lexical differences between Languedoc and Gascon Occitan. To avoid repeating rules, in order to facilitate readability and maintenance, I write things like:

```
  <!-- pas >> pas, mai/shens -->
  <rule weight="0.8">
    <match lemma="pas" tags="adv"><select lemma="pas"/></match>
  </rule>
  <rule weight="1.0">
    <or> 
      <match lemma="pas" tags="adv"><select lemma="mai"/></match>
      <match lemma="pas" tags="adv"><select lemma="shens"/></match>
    </or>
    <match lemma="que" tags="cnjsub"/>
  </rule>
```

... where `mai` is the word in Languedocian and `shens` the Gascon one.

In the bidixes only `mai` or `shens` are declared. For instance, in `.deps/fra-oci@gascon.dix` we have:

```
<e>       <p><l>pas<s n="adv"/></l>               <r>pas<s n="adv"/></r></p></e>
<e><p><l>shens<s n="adv"/></l>   <r>pas<s n="adv"/></r></p></e>
```

But, for some unknown reason, there is not a match in Gascon:

```
$ echo "je ne veux pas qu'un euro" | apertium -d . fra-oci_gascon-lextor
1:SELECT:1:ne<adv>:3:ne<adv><enon>
1:SELECT:0.8:pas<adv>:2:pas<adv>
^je<prn><tn><p1><mf><sg>/jo<prn><tn><p1><mf><sg>$ ^ne<adv>/ne<adv><enon>$ ^vouloir<vblex><pri><p1><sg>/voler<vblex><tv><pri><p1><sg>$ ^pas<adv>/pas<adv>$ ^que<cnjsub>/que<cnjsub>$ ^un<det><ind><m><sg>/un<det><ind><m><sg>$ ^euro<n><m><sg>/èuro<n><m><sg>$^.<sent>/.<sent>$
```

(Notice that:
```
$ echo "je ne veux pas qu'un euro" | apertium -d . fra-oci_gascon-biltrans
^je<prn><tn><p1><mf><sg>/jo<prn><tn><p1><mf><sg>$ ^ne<adv>/ne<adv><enon>/non<adv>/pas<adv>$ ^vouloir<vblex><pri><p1><sg>/voler<vblex><tv><pri><p1><sg>$ ^pas<adv>/pas<adv>/shens<adv>$ ^que<cnjsub>/que<cnjsub>$ ^un<det><ind><m><sg>/un<det><ind><m><sg>$ ^euro<n><m><sg>/èuro<n><m><sg>$^.<sent>/.<sent>$
hector@bestia:~/apertium/apertium-oci-fra$ 
```
)

On the other hand, it is working for Languedocian:
```
$ echo "je ne veux pas qu'un euro" | apertium -d . fra-oci-lextor
1:SELECT:0.8:ne<adv>:2:non<adv>
1:SELECT:1:pas<adv>:2:mai<adv>
^je<prn><tn><p1><mf><sg>/ieu<prn><tn><p1><mf><sg>$ ^ne<adv>/non<adv>$ ^vouloir<vblex><pri><p1><sg>/voler<vblex><tv><pri><p1><sg>$ ^pas<adv>/mai<adv>$ ^que<cnjsub>/que<cnjsub>$ ^un<det><ind><m><sg>/un<det><ind><m><sg>$ ^euro<n><m><sg>/èuro<n><m><sg>$^.<sent>/.<sent>$
```

If two rules are written, it works:
```
  <rule weight="1.0">
    <match lemma="pas" tags="adv"><select lemma="mai"/></match>
    <match lemma="que" tags="cnjsub"/>
  </rule>
  <rule weight="1.0">
    <match lemma="pas" tags="adv"><select lemma="shens"/></match>
    <match lemma="que" tags="cnjsub"/>
  </rule>
```

In this particular case, the rule is straightforward. There is not a big problem to duplicate it. But in other cases there are chains of quite more complex rules. It would be much better to be able to write everything in a more compact way.

**Comment by mr-martian** [comment]
Due to the way rules are processed internally, I'm not sure there's any good way to get that rule working as written.

I think the simplest solution might be a metalrx-type script where you could write

```xml
  <!-- pas >> pas, mai/shens -->
  <rule weight="0.8">
    <match lemma="pas" tags="adv"><select lemma="pas"/></match>
  </rule>
  <rule weight="1.0">
    <or> 
      <match lemma="pas" tags="adv">
        <select lemma="mai" v="Lang"/>
        <select lemma="shens" v="Gasc"/>
      </match>
    </or>
    <match lemma="que" tags="cnjsub"/>
  </rule>
```

and then the script would generate one copy with `<select lemma="mai" v="Lang"/>` deleted and one with `<select lemma="shens" v="Gasc"/>` deleted.

**Comment by hectoralos** [comment]
Perfect for me. If the `v` is added, it would be probably good to have it also in other places: in `<rule>` quite sure, and maybe also in `<match>`.

**Comment by hectoralos** [comment]
@mr-martian , is the problem caused because `mai` does not exist in the Gascon dictionary, or because a `<select>` clause should not be inside an `<or>`? In fra-cat, for instance, I am using this kind of structure for managing words that have the same behaviour, and I haven't notice any misfunctioning. For instance:
```
  <rule weight="0.8">
    <or>
      <match lemma="molt" tags="preadv"><select lemma="très"/></match>
      <match lemma="gaire" tags="preadv"><select lemma="très"/></match>
      <match lemma="no molt" tags="preadv"><select lemma="pas très"/></match>
      <match lemma="no gaire" tags="preadv"><select lemma="pas très"/></match>
    </or>
  </rule>
  <rule weight="1.0">
    <or>
      <match lemma="molt" tags="preadv"><select lemma="beaucoup"/></match>
      <match lemma="gaire" tags="preadv"><select lemma="beaucoup"/></match>
      <match lemma="no molt" tags="preadv"><select lemma="pas beaucoup"/></match>
      <match lemma="no gaire" tags="preadv"><select lemma="pas beaucoup"/></match>
    </or>
    <or>
      <match lemma="més"/>
      <match lemma="menys"/>
      <match lemma="menor"/>
      <match lemma="major"/>
      <match lemma="pitjor"/>
      <match lemma="millor"/>
      <match lemma="més amunt"/>
      <match lemma="més avall"/>
      <match lemma="més aviat"/>
      <match lemma="més tard"/>
      <match lemma="més endavant"/>
      <match lemma="més enllà"/>
    </or>
  </rule>

```

**Comment by mr-martian** [comment]
The problem is that you have two `<match>` blocks with the same source lemma, so if it encounters that lemma in the input, it looks up the associated select, of which it only knows how to handle 1.

As for where `v=` can go, if I'm applying it to more than one element, it's easiest for me to let it just be on every element.

**Comment by hectoralos** [comment]
I understand now the logic of the problem. It seems that it really will happen only when there are different variants of a language, so `v=` will be a good solution. It will be useful for other elements too, and I don't think it may hurt elsewhere, do perfect for your solution.

**Comment by mr-martian** [comment]
The relevant script is now in `apertium`, and for what I wrote above, you would probably want `apertium-filter-xml Gasc apertium-oci-fra.fra-oci.lrx .deps/fra-oci@gascon.lrx`, which will handle `v=` on any element other than `<lrx>` (on the assumption that we don't want to delete the entire document).
