### ISSUE TITLE
feature request: has-lemq attribute?

### ISSUE THREAD

**Issue by unhammer** [apertium/apertium-lex-tools#90]
I'd love to be able to write

     <match tags="*.cmp"><remove has-lemq="true"/></match>

so I can avoid using MWE's in compounds (`printe→skrive# ut` normally, but don't want "printeprosessen" to turn into `skrive# utprosessen`), without having to list all MWE's in the .lrx.

**Comment by unhammer** [comment]
`  <rule>           <match tags="*.cmp"><remove contains="#"/></match></rule>
`
would also solve it (even better), but doesn't seem to work (removes all readings now)

**Comment by unhammer** [comment]
it works :fireworks:

**Comment by unhammer** [comment]
Actually I think there may be a bug still.

`  <rule weight="1.3" c="prefer numbers without :e"> <match tags="adj.ord.*"><remove suffix=":e"/></match></rule>`

works but

`  <rule weight="1.3" c="prefer numbers without :e"> <match tags="adj.ord.*"><remove contains=":e"/></match></rule>`

doesn't, for input

`^1.<adj><ord><pst><nt><sg><ind>/2:REMOVE:1.3:1.<adj><ord><pst><nt><sg><ind>:2:1:e<adj><ord><pst><fn><sg><ind>
1<adj><ord><pst><fn><sg><ind>$
`

(or is `contains` meant to be a sort of "strictly less than"?)

**Comment by mr-martian** [comment]
I copied the prior behavior where `lemma="X"` matches `X`, `suffix="X"` matches `.+X`, and `contains="X"` matches `.+X.+`, though `.*` would probably be more in line with what people would expect it to do.

**Comment by unhammer** [comment]
hm, maybe strictly-contains is useful for people … @ftyers @jonorthwash @hectoralos thoughts?

**Comment by hectoralos** [comment]
I even didn't know that "contains" or "suffix" exist. Where are they documented?

**Comment by mr-martian** [comment]
Looks like they were added by @ftyers in 371b3740e74c27a2e6ff4278ce9286ee9e0b2319 and 8f5493f28d944c9c1591e3449f6df8c4718ab2c6 (June 2020), but I'm not aware of any documentation.

**Comment by hectoralos** [comment]
Seemingly, even the case is now available. I was waiting for this, but had no idea it had been implemented one year and a half ago. We really have a serious problem of communication and documentation.

**Comment by unhammer** [comment]
```
$ wc ChangeLog NEWS
0 0 0 ChangeLog
0 0 0 NEWS
0 0 0 total
```

yes

**Comment by jonorthwash** [comment]
> hm, maybe strictly-contains is useful for people … @ftyers @jonorthwash @hectoralos thoughts? (currently` contains="bc"` matches the input lemma "abcd" but not "abc" or "bcd" or "bc")

The current behaviour of `contains` sounds semantically appropriate.  Perhaps we need something else for strict matching?

**Comment by unhammer** [comment]
By "strictly-contains" I meant strict as in strict/proper subset. That's what the current contains does. And I find that behaviour surprising – typically functions called things like contains/includes don't start returning false just because inputs are equal (e.g. https://www.php.net/manual/en/function.str-contains.php https://hackage.haskell.org/package/MissingH-1.4.3.0/docs/Data-List-Utils.html#v:contains )

**Comment by xavivars** [comment]
If I read properly this....

> currently contains="bc" matches the input lemma "abcd" but not "abc" or "bcd" or "bc"

it seems wrong.

contains="bc" should match all these inputs: "abcd", "abc", "bcd" and "bc" to work as I would have expected.

**Comment by jonorthwash** [comment]
Ah, I see.  Yes, then, agreed with @xavivars, @mr-martian, etc.

**Comment by unhammer** [comment]
made it an issue of its own since the original one here is solved
