### ISSUE TITLE
sentence end in LRX 

### ISSUE THREAD

**Issue by jaumeortola** [apertium/apertium-lex-tools#95]
I used this pattern in LRX rules to match any token except a sentence end (most tags have at least two components separated by a dot, except a few: adv, pr, cm...). It doesn't work anymore. Is there any other way to get the same result? @mr-martian 
```
    <repeat from="0" upto="10">
      <or>
        <match tags="*.*"/>
        <match tags="adv"/>
        <match tags="pr"/>
        <match tags="cnjcoo"/>
        <match tags="cm"/>
      </or>
    </repeat>
```

**Comment by mr-martian** [comment]
If you're using the new `glob="plus"` option, then `*` is zero or more tags. `?.+` (any tag followed by 1 or more tags) should work.

**Comment by jaumeortola** [comment]
Thanks. Perfect. It works as expected.
