### ISSUE TITLE
Add tags in calls to sequences

### ISSUE THREAD

**Issue by hectoralos** [apertium/apertium-lex-tools#99]
I have several sequences with tens and even hundreds of elements. As a rule, every element has a morphological tag, and it is the same in the whole list: `n.*`, `adj.*`, etc. It happens that I want to use a sequence, but, say, I want specifically plural nouns, not any form of the lemmas in the sequence. For this I have to duplicate the list. This is not good for readability nor maintainability. I propose to have something like:
`<seq n="personas" tags="n.*.pl"/>`
The label `tags` should replace the one defined for every element of the list or be added if the element does not have a tag.

**Comment by mr-martian** [comment]
Due to how `<def-seq>` is processed, doing exactly what you've suggested is rather difficult, but something I could do instead is
```xml
<def-set n="personas" tags="n.*">
  <lemma>Henry</lemma>
  <lemma>Alfred</lemma>
  ...
</def-set>
```
And then `<set n="personas"/>` would be all those lemmas with the default tags `n.*` and `<set n="personas" tags="n.*.pl"/>` would replace the tags as you suggest.

**Comment by hectoralos** [comment]
Seems good but, looking at my actual use of sequences I find a problem. In Romance languages nouns and adjectives are often pretty similar, so I have:

```
    <def-seq n="gentilicis_n"><or>
      <match lemma="abbassida" tags="n.*"/>
      <match lemma="abcaz" tags="n.*"/>
      <match lemma="acadian" tags="n.*"/>
      <match lemma="afganés" tags="n.*"/>
    </or></def-seq>
```

and

```
    <def-seq n="gentilicis_adj"><or>
      <match lemma="abbassida" tags="adj.*"/>
      <match lemma="abcaz" tags="adj.*"/>
      <match lemma="acadian" tags="adj.*"/>
      <match lemma="afganés" tags="adj.*"/>
    </or></def-seq>
```

Seemingly, with the given syntax I couldn't reuse the lemma list.


And there is a second less important problem. I have a list of currencies like this one:

```
    <def-seq n="monnaies"><or>
      <match lemma="euro" tags="n.*"/>
      <match lemma="dollar" tags="n.*"/>
      <match lemma="livre" tags="n.f.*"/>
      <match lemma="yen" tags="n.*"/>
      <match lemma="yuan" tags="n.*"/>
    </or></def-seq>
```

The question here is that _livre_ must be `n.f.*` instead of just `n.*` because _livre_ `n.m.* `has another meaning (_book_ instead of _pound_). So, if not too difficult, it would be good if we could underspecify tags at the lemma level. Of course, this makes the set redefinition (as `tags="n.*.pl"`, for instance) more difficult.

**Comment by mr-martian** [comment]
The first instance could easily be handled in this syntax with `<set ... tags="adj.*"/>` and `<set ... tags="n.*"/>`. The tag specification in the definition is just a default to use when you don't specify an override.

As for the second case, I can handle that if we change "replacing tags" to "appending tags", and have something like
```xml
<def-set n="monnaies">
  <match lemma="euro" tags="n"/>
  <match lemma="dollar" tags="n"/>
  <match lemma="livre" tags="n.f"/>
  <match lemma="yen" tags="n"/>
  <match lemma="yuan" tags="n"/>
</def-set>

<set n="monnaies" tags="*"/> <!-- any money word -->
<set n="monnaies" tags="*.pl"/> <!-- any plural money word -->
```
But how common is that situation? Maybe it would be better to stick with the simpler version and keep the currency list in a `<def-seq>`?

**Comment by mr-martian** [comment]
Surveying `oci-fra`, it looks like your `<def-seq>`s have 0-3 words with variant tags in an overall list of 10-1000.

**Comment by hectoralos** [comment]
I agree the case of "monnaies" and "livre" is very uncommon, so don't worry. I was just explaining all the issues I saw.

As for "gentilicis__n" and "gentilicis__adj", I don't see how it will be resolved as you say. I see that this could be done:
```
    <def-seq n="gentilicis"><or>
      <match lemma="abbassida"/>
      <match lemma="abcaz"/>
      <match lemma="acadian"/>
      <match lemma="afganés"/>
    </or></def-seq>

    <def-set n="gentilicis_n" tags="n.*">
      <seq n="gentilicis"/>
    </def-set>
    <def-set n="gentilicis_adj" tags="adj.*">
      <seq n="gentilicis"/>
    </def-set>
```

**Comment by mr-martian** [comment]
This is what I was imagining for that scenario:
```xml
    <def-set n="gentilicis" tags="n.*">
      <lemma>abbassida</lemma>
      <lemma>abcaz</lemma>
      <lemma>acadian</lemma>
      <lemma>afganés</lemma>
    </def-set>

    <def-seq n="gentilicis_n">
      <set n="gentilicis"/> <!-- or tags="n.*" -->
    </def-seq>
    <def-seq n="gentilicis_adj">
      <set n="gentilicis" tags="adj.*"/>
    </def-seq>
```

**Comment by hectoralos** [comment]
Ok. I see, This will do the job perfectly. The only thing that worries me a little bit is that sets will be extremely similar to sequences. The differences will have to be clearly explained, because they are not trivial. In the vast majority of cases, sequences can be expressed as sets, even in a more compact form. Sequences are likely to become residual. I see also that for sets the `<or>...</or>` in the list probably won't be necessary.

**Comment by mr-martian** [comment]
Pushed this as version `0.5.0`.

The distinction between `<def-set>` and `<def-seq>` is similar to the CG distinction between `LIST` and `TEMPLATE`. If most of what you need is lists of lemmas, then `LIST`/`<def-set>` is usually what you want, but every once in a while you need to reuse a more complicated pattern, and that's what `TEMPLATE`/`<def-seq>` is for.
